const SOCKET_CONNECTION = "connection";
const SOCKET_CHAT_CONVERSATIONS = "chats";
const SOCKET_CHAT_CONVERSATION = "conversation";
const SOCKET_CHAT_SEND = "chat";
const SOCKET_ORDER_BUSINESS_NOTIFY = "event-notification-business";
const SOCKET_ORDER_BUSINESS_RECEPT = "event-received-order";
const SOCKET_ORDER_BUSINESS_REJECT = "event-reject-order";
const SOCKET_ORDER_BUSINESS_ACCEPT = "event-rider-search";
const SOCKET_ORDER_BUSINESS_DELIVERED = "event-delivered-order";
const SOCKET_ORDER_BUSINESS_MY_RIDER = "event-order-business-my-rider";
const SOCKET_ORDER_BUSINESS_VERIFY = "event-order-business-verify";
const SOCKET_ORDER_BUSINESS_DELAY = "event-order-business-delay";
const SOCKET_ORDER_BUSINESS_CHANGE_ID = "event-order-business-update-id";
const SOCKET_ORDER_BUSINESS_COMPLETE = "event-order-business-complete";
const SOCKET_RIDER_SHARE_COORDS = "event:rider:share:coords"

export {
  SOCKET_CONNECTION,
  SOCKET_CHAT_CONVERSATIONS,
  SOCKET_CHAT_CONVERSATION,
  SOCKET_CHAT_SEND,
  SOCKET_ORDER_BUSINESS_NOTIFY,
  SOCKET_ORDER_BUSINESS_RECEPT,
  SOCKET_ORDER_BUSINESS_REJECT,
  SOCKET_ORDER_BUSINESS_ACCEPT,
  SOCKET_ORDER_BUSINESS_DELIVERED,
  SOCKET_ORDER_BUSINESS_MY_RIDER,
  SOCKET_ORDER_BUSINESS_VERIFY,
  SOCKET_ORDER_BUSINESS_DELAY,
  SOCKET_ORDER_BUSINESS_CHANGE_ID,
  SOCKET_ORDER_BUSINESS_COMPLETE,
  SOCKET_RIDER_SHARE_COORDS,
};